// <auto-generated />
namespace console_app.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class remove_increment : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(remove_increment));
        
        string IMigrationMetadata.Id
        {
            get { return "202006071031220_remove_increment"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
